import type { Metadata } from 'next';

export const homeMetadata: Metadata = {
  title: 'Best Coding Courses for Kids | Robotics Training | AI & ML Programs | CodeKids Technologies',
  description: 'India\'s #1 coding courses for kids and students. Learn robotics, AI, machine learning, full stack development, and job-ready tech skills. Best coding classes for children, robotics training, and STEM education programs. Trusted by 1000+ students and 20+ schools.',
  keywords: [
    'coding courses for kids',
    'best coding classes for children',
    'robotics training for students',
    'AI courses for kids',
    'machine learning courses',
    'full stack development course',
    'coding classes online',
    'robotics classes India',
    'programming courses for kids',
    'STEM education India',
    'tech courses for students',
    'coding school online',
    'best coding institute India',
    'coding bootcamp India',
    'learn coding for kids',
    'robotics education',
    'AI education for kids',
    'data science courses',
    'cybersecurity training',
    'web development course',
    'app development training',
    'IoT courses',
    '3D printing courses',
    'drone programming classes',
    'CodeKids Jr',
    'CodeKids Pro',
    'CodingJr',
    'Coding Pro',
    'school coding programs',
    'college tech courses',
    'job-ready tech skills',
    'online coding classes India',
    'offline coding training',
    'STEM lab setup',
    'teacher training programs',
  ],
  openGraph: {
    title: 'Best Coding Courses for Kids | Robotics Training | AI Programs | CodeKids',
    description: 'India\'s #1 coding courses for kids. Learn robotics, AI, machine learning, and job-ready tech skills. Trusted by 1000+ students and 20+ schools.',
    url: 'https://codekids.tech',
    siteName: 'CodeKids Technologies',
    images: [
      {
        url: 'https://codekids.tech/assest/codekids_finallogo.jpg',
        width: 1200,
        height: 630,
        alt: 'CodeKids Technologies - Best Coding Courses for Kids',
      },
    ],
    locale: 'en_IN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Best Coding Courses for Kids | Robotics Training | CodeKids Technologies',
    description: 'India\'s #1 coding courses for kids. Learn robotics, AI, machine learning, and job-ready tech skills.',
    images: ['https://codekids.tech/assest/codekids_finallogo.jpg'],
  },
  alternates: {
    canonical: 'https://codekids.tech',
  },
};

